name: Redeploy to Fly.io

on:
  workflow_dispatch:
    inputs:
      source_repo_url:
        description: 'Source repository URL'
        required: true
      fly_api_token:
        description: 'Fly.io API Token'
        required: true
      fly_app_name:
        description: 'Fly.io App Name'
        required: true
      docker_image:
        description: 'Docker image to deploy'
        required: true
        default: 'registry.fly.io/needware-app:latest'
      client_id:
        description: 'Client ID for callback'
        required: true
      github_token:
        description: 'GitHub Token'
        required: true

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
        with:
          version: '0.3.94'

      - name: Clone source repository
        run: |
          git clone ${{ github.event.inputs.source_repo_url }} /tmp/source-repo
          cd /tmp/source-repo

      - name: Create fly.toml
        run: |
          cd /tmp/source-repo
          cat << 'EOF' > fly.toml
          app = '${{ github.event.inputs.fly_app_name }}'
          primary_region = 'sin'

          [build]
            image = '${{ github.event.inputs.docker_image }}'

          [http_service]
            internal_port = 8080
            force_https = true
            auto_stop_machines = 'suspend'
            auto_start_machines = true
            min_machines_running = 0
            max_machines_running = 1
            processes = ['app']

          [[vm]]
            memory = '1gb'
            cpu_kind = 'shared'
            cpus = 1
            memory_mb = 1024
          EOF

      - name: Deploy to Fly.io
        env:
          FLY_API_TOKEN: ${{ github.event.inputs.fly_api_token }}
        run: |
          cd /tmp/source-repo
          flyctl deploy --app ${{ github.event.inputs.fly_app_name }} --remote-only

      - name: Verify deployment
        run: |
          echo "Redeployed to: https://${{ github.event.inputs.fly_app_name }}.fly.dev"
